### ISSUE TITLE
Every. Single. Time. I. Reboot. I. Have. To. Do. The. Whole. Process. Over. Again.

### ISSUE THREAD

**Issue by lucisnashans** [palera1n/palen1x#13]
This is so infuriating. I had a live Linux distro on my usb stick it worked flawlessly but took a long time. I just had to keep my lab top open all night. With this when I reboot on my iPhone X iOS 15.4.1 I always get stuck at apple logo and have to do everything over again. I miss when jailbreaking was simple and fun. Now it’s just a mess.

**Comment by RealKGB** [comment]
Sir you are complaining that the jailbreak works as intended.

**Comment by haloteanix** [comment]
> This is so infuriating. I had a live Linux distro on my usb stick it worked flawlessly but took a long time. I just had to keep my lab top open all night. With this when I reboot on my iPhone X iOS 15.4.1 I always get stuck at apple logo and have to do everything over again. I miss when jailbreaking was simple and fun. Now it’s just a mess. 

dumbass thats how the jailbreak works.

**Comment by lucisnashans** [comment]
It makes me recreate the whole ffs and everything also you don’t have to be condescending lmfao

**Comment by lucisnashans** [comment]
I’ve used tutorials (written) and it never says you have to do EVERYTHING over again only rejailbreak and done not recreate the whole ffs time and time again but again the tut could be wrong

**Comment by flowerible** [comment]
> This is so infuriating. I had a live Linux distro on my usb stick it worked flawlessly but took a long time. I just had to keep my lab top open all night. With this when I reboot on my iPhone X iOS 15.4.1 I always get stuck at apple logo and have to do everything over again. I miss when jailbreaking was simple and fun. Now it’s just a mess.

Unfortunately, due to how the jailbreak process for rootful works, there's no denying that the experience is pretty shit. You can blame iOS 15.0+ for that. (don't forget palen1x uses palera1n-c **beta** 4)

There's several bugs for rootful that rootless doesn't have on iOS 15.0+ which is nice, I guess. What you're experiencing is obviously not intended to happen, and there's not much the developer of palera1n-c can do about it currently; it doesn't seem to even happen to them, which makes it hard to work with.

There's also rootless, which is most likely where most jailbreaks will be headed in the future and which is another option for jailbreaking; however, it's definitely not something to use *yet*, although the installing process and jailbreak experience is extremely fast there's really no developers using it (currently) because of the lack of resources available (tweak injection, rootless Theos pull request).

**Comment by lucisnashans** [comment]
I known you had to do the last step over and over again after reboot but it makes me make me restore the ffs and then create it then jailbreak every blog post/written guide always says that you’ll only have to do the second part over again not the whole process

**Comment by flowerible** [comment]
Not much you can do really anyway, other than wait for rootless which won't have fakefs/bindfs issues

**Comment by lucisnashans** [comment]
> Not much you can do really anyway, other than wait for rootless which won't have fakefs/bindfs issues

Thank you sm for the response and not being an ass like the other dude who misread my issue I’ll just wait for more updates/fixes or rootless :)

**Comment by buzzcoding** [comment]
You do not have to recreate the fakefs every time you want to jailbreak. It can persist through reboots. That is the reason it exists. When your device seems to be stuck on the Apple logo, that is called download mode. All you need to do is unplug and replug the lightning cord on the device so that palen1x will redetect it and rejailbreak it. I was very confused until I figured this out, too. After it boots, you can tap Tools->Do All in the palera1n loader app.
