### ISSUE TITLE
[Suggestion] Use GitHub Releases to upload the ISO files

### ISSUE THREAD

**Issue by moritz-t-w** [palera1n/palen1x#3]
Would be a nicer way to organize them

**Comment by TheMasterOfMike** [comment]
Honestly would solve the fact that I’ve had to hardcode the download link for palen1x on the guide ~~(and may or may not have been able to update it because this laptop died somehow and I’m currently trying to get my Late 2011 15” set up with the stuff I need to not have to use a browser to update it)~~

**Comment by m00nl1ghts** [comment]
i agree

**Comment by Beast9265** [comment]
> i agree

true

**Comment by junepark678** [comment]
nick chan cdn on top

**Comment by m00nl1ghts** [comment]
> nick chan cdn on top

wen eta better ux

**Comment by junepark678** [comment]
fr

**Comment by moritz-t-w** [comment]
> > i agree
> 
> true

> yeah

**Comment by moritz-t-w** [comment]
> > i agree
> 
> true

yeah

**Comment by moritz-t-w** [comment]
> 

@junepark678
doesn't have to be mutually exclusive, it's even better to offer multiple mirrors, and better yet when they are both cdns

**Comment by junepark678** [comment]
ig
but nick chan cdn is still ON TOP :trollface:

**Comment by moritz-t-w** [comment]
sure

**Comment by flowerible** [comment]
I've added releases: https://github.com/palera1n/palen1x/releases
@TheMasterOfMike @moritz-t-w 

Though I'm still gonna be using the cdn for testing, thanks for the suggestion.

**Comment by moritz-t-w** [comment]
Thanks I appreciate that!
